### ISSUE TITLE
Use of red and blue colors in shallow water plots

### ISSUE THREAD

**Issue by ketch** [clawpack/riemann_book#127]
Currently we use red and blue to distinguish water that started to the left/right of x=0.  We also use these two colors to distinguish shocks/Hugoniot loci versus rarefactions/integral curves.  I wonder if it would be better to change one of these to prevent the reader from thinking that they are somehow related.

For instance, we could just use blue and green in the shallow water plots.

**Comment by rjleveque** [comment]
Blue and green seems ok.  Or we could just use 4 shades of blue, 2 on each side of the discontinuity to make it clear that it's all water.
