### ISSUE TITLE
Eq. in acoustics NB

### ISSUE THREAD

**Issue by maojrs** [clawpack/riemann_book#155]
I think I found an error in the acoustics NB in the solution by characteristics. The equation $w=\alpha_1 r_1 + \alpha_2 r_2$, should read either $q=\alpha_1 r_1 + \alpha_2 r_2$ or $q=w_1 r_1 + w_2 r_2$. I thought it was just a typo, but in the interactive below is this equation that is represented. David, I think you wrote this part, so I wanted to check with you before correcting anything.

**Comment by ketch** [comment]
You are right; thanks for catching those.  I've submitted a PR with corrections.

I noticed one other thing in acoustics that I think we should clean up.  In Section 1.5 we essentially repeat exactly the same plots, first in an interact but with no phase plane, and then with a phase plane but no interact.  This seems silly -- wouldn't it be better to have a single set of plots for each example?

**Comment by maojrs** [comment]
Thanks for the fix. I have been thinking the same about the repetitive plots. I merged your pull request. I will do another pull request with some rearrangements of the plots and interacts.
