### ISSUE TITLE
Burgers interact

### ISSUE THREAD

**Issue by maojrs** [clawpack/riemann_book#185]
I took a look at the interact not working in burgers. The problems seems to be this line:

`from utils.snapshot_widgets import interact`
should be
`from ipywidgets import interact`

If we use the first one, we get the snapshots as we want right? If we use the second one then we get the interacts. If I remember correctly the script to produce the pdf changed all the `from ipywidgets import  interact` to `from utils.snapshot_widgets import interact`. Maybe we should add to the script to revert everything once the pdf is generated.

I am happy to do that but just want to check with you guys since I didn't write that part, and I don't want to break anything else. 

I also noticed an additional parameter was added to `burgers_demos.multivalued_solution` and `burgers_demos.shock_location` To fix the interact. I don't think this was necessary, we just need to change the import statement on the top of the notebook. 

Should I just revert these changes to the original or am I missing something?

**Comment by maojrs** [comment]
Maybe the confusion comes from having interact being imported inside the notebook and then also in `exact_solvers/burgers.py`?

**Comment by rjleveque** [comment]
I think `burgers.py` was the only file in `exact_solvers` that imported from `utils.snapshot_widgets`, must have been a mistake.  I replaced that by the usual import and now the notebook works fine.  Thanks!
