### ISSUE TITLE
Second equation of subsection 9.1.3

### ISSUE THREAD

**Issue by MGYBY** [clawpack/riemann_book#236]
The book "Riemann Problem and Jupyter Solutions" is thought-provoking and eye-opening and I really enjoy reading it. When I was reading subsection 9.1.3, I found that the subscript x for the second term in the second equation was omitted for some reason.

**Comment by maojrs** [comment]
Thank you @MGYBY . I just made a pull request #237 with the typo correction. It should be approved in the following days, and the master branch should be fixed. Please let us know if you find any other typos.

**Comment by rjleveque** [comment]
Yes, thanks @MGYBY.  I merged this fix and also added it to the [errata page](http://www.clawpack.org/riemann_book/errata.html).
