### ISSUE TITLE
Tamman EOS notebook generates errors

### ISSUE THREAD

**Issue by ketch** [clawpack/riemann_book#32]
@maojrs I thought I successfully ran this notebook back when it was added, but I must be wrong since it doesn't work for me now and it hasn't been changed.

The second code cell gives me an error about passing 5 arguments to  `phi_exact`.  I was able to fix that, but then I get an error about `ul` being undefined.  Does the notebook run for you?

**Comment by maojrs** [comment]
It does not really matte since I just did a major update of the notebook. Now it uses riemann_tools,  and I also tried to follow a similar approach than the one used with the ideal gas Euler eqs. I am still working on it, but I will make a pull request in case you want to merge it.
