### ISSUE TITLE
plot_chars in make_plot_function (riemann_utils.py)

### ISSUE THREAD

**Issue by maojrs** [clawpack/riemann_book#53]
I am trying to set plot_chars = True while calling make_plot_function, but I keep getting an error. I think there might be a bug since this is called:
plot_characteristics(states,speeds,plot_chars,ax[0])

and the function actually takes:
plot_characteristics(reval, char_speed, axes=None, extra_lines=None).

**Comment by ketch** [comment]
@maojrs Please read the docstring of `make_plot_function`.  It includes this:

>    plot_chars: If provided, ordinary characteristics are included in the x-t plot.
                The value of this argument should be a function c(q,x) that gives
                the characteristic speed.

**Comment by ketch** [comment]
You are right, though, about the bug.  If you look at other notebooks you'll notice that I'm just calling plot_characteristics directly, so I forgot to change that call when I upgraded the function.   Feel free to fix it, or I will do so soon.
