### ISSUE TITLE
riemann_tools.make_plot_function for primitive variables

### ISSUE THREAD

**Issue by maojrs** [clawpack/riemann_book#54]
@ketch I am trying to use riemann_tools.make_plot_function to plot the primitive variables for the Euler Tammann, but it does not scale the ranges properly since it does the scaling for the conserved variables.
In the example I am showing, the primitive variables are much more relevant than the conserved ones. It would be nice if we can add this functionality or at least some added parameter to force which plotting range is used. I have a couple of ideas on how to do this but thought to check with you in case I am missing something that is already there. Maybe forcing the plotting range could be a better choice, so we can also zoom in into very small waves.

**Comment by ketch** [comment]
I wanted this for the Euler notebooks anyway, so I went ahead and added it.  Changing the plotting ranges can also be done; it's just going to be a little messy since there are several plots, so you need to specify both which plot and what bounds you want to set.

**Comment by maojrs** [comment]
Great! I will give it a try. Thanks

**Comment by ketch** [comment]
I'm closing this since I think it was resolved in #56.
