### ISSUE TITLE
Electronic material that needs to be adapted for the print book

### ISSUE THREAD

**Issue by ketch** [clawpack/riemann_book#79]
There are a few things that still read funny in the PDF and need to be modified to work there:

- [ ] At the end of the introduction, the interactive phase planes for acoustics and shallow water.  Can we host these HTML files somewhere (Github doesn't seem to work for that) and put a hyperlink in?

**Comment by rjleveque** [comment]
I suggest we create a gh-pages branch for showing the rendered notebooks.

I did this on my fork, visible at http://rjleveque.github.io/riemann_book/

If @ketch and @maojrs like it, I can push the branch to this repository.

**Comment by ketch** [comment]
I really like this!  Please do push it to the main repo.

**Comment by rjleveque** [comment]
Done.  Now visible at: http://www.clawpack.org/riemann_book/

There are still some glitches in the html files I'll work on some more.
