### ISSUE TITLE
Create pdf in build_pdf directory?

### ISSUE THREAD

**Issue by rjleveque** [clawpack/riemann_book#84]
@ketch: I suggest we 

- consolidate `make_chapters.py` and `make_book.sh` into `make_pdf.py` similar to `make_html.py` so it's less confusing where things are done and where the specify the desired chapters.

- Build the pdf file in a new directory `build_pdf` so that all the files generated `0*.ipynb`, `riemann.aux`, etc. don't end up cluttering up the main directory.  Then move the `pdf` file out of this directory so it can be safely deleted to clean up.  This would be similar to what's done in #83 for html files.

**Comment by ketch** [comment]
Yes, my original implementation was hacky and this sounds good.  I will try to do this tomorrow.
